// <auto-generated />
using System;
using HighscoreAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HighscoreAPI.Migrations
{
    [DbContext(typeof(HighscoreDataContext))]
    [Migration("20200401075158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("HighscoreAPI.Model.Highscore", b =>
                {
                    b.Property<Guid>("HighScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HighScoreId");

                    b.ToTable("HighscoreLists");
                });
#pragma warning restore 612, 618
        }
    }
}
